version: '3'
services:
  app:
    container_name: shomanapi
    restart: always
    build: .
    ports:
      - '4040:4000'
    links:
      - mongo
  mongo:
    container_name: shomanmongo
    image: mongo
    ports:
      - '27018:27017'
