version: '3'
services:
  app:
    container_name: shomanapi
    restart: always
    build: .
    ports:
      - '4040:4000'
    depends_on:
    - mongo
  mongo:
    container_name: shomanmongo
    image: mongo
    ports:
      - '27018:27017'
    volumes: 
    - mongo-volume:/data/db
volumes: 
  mongo-volume:
